// <auto-generated />
namespace ShopHere.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ImageUrl_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageUrl_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202006291022534_ImageUrl_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
